// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsInteractiveService.Shared")>]
[<assembly: AssemblyProductAttribute("FsInteractiveService")>]
[<assembly: AssemblyDescriptionAttribute("F# interactive service API exposed via a lightweight HTTP server")>]
[<assembly: AssemblyVersionAttribute("0.2.1")>]
[<assembly: AssemblyFileVersionAttribute("0.2.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsInteractiveService.Shared"
    let [<Literal>] AssemblyProduct = "FsInteractiveService"
    let [<Literal>] AssemblyDescription = "F# interactive service API exposed via a lightweight HTTP server"
    let [<Literal>] AssemblyVersion = "0.2.1"
    let [<Literal>] AssemblyFileVersion = "0.2.1"
